Практика 2
AlexandrBorodinov/MMAD pull request #2
Opened 2021-04-13 20:46 UTC by AlexandrBorodinov

Выполнение заданий из практики 2.

2021-04-19 03:20 UTC, stanislavlyalin requested changes

2021-04-19 03:20 UTC, stanislavlyalin commented on pract2/run.py
> +print("\nЗАДАНИЕ 4")
Приведите, пожалуйста, в комментариях формулировки каждого задания, чтобы проще было проверять

2021-04-19 03:20 UTC, stanislavlyalin commented on pract2/run.py
> +            arraymax = array
Приведу замечания сразу ко всей функции. Функция должна искать массив с наибольшей суммой элементов, а не генерировать массивы, поэтому создание массивов должно быть снаружи функции. Параметры `n` и `len` тогда будут не нужны, а нужен будет 1 параметр - массив массивов или список аргументов переменной длины (лучше второе).
Делать `print` внутри функции тоже не нужно. Пусть она только возвращает массив, а печать будет снаружи.
Предварительно заполнять массив нулями при генерации тоже нет необходимости. Можно сразу же заполнять случайными значениями.
Вообще, я смог придумать такое решение:
```python
def arrayWithMaxElementsSum(*arrays):
	return arrays[max(enumerate(arrays), key=lambda pair: sum(pair[1]))[0]]
```

Можете воспользоваться этим решением или придумать своё.

2021-04-19 03:20 UTC, stanislavlyalin commented on pract2/run.py
> +    number = list(''.join(input('Введите число: ')))
Ввод числа должен быть вне функции

2021-04-19 03:20 UTC, stanislavlyalin commented on pract2/run.py
> +    print('%s %s %s' % (hund[int(h)], dec[int(d)], one[int(o)]))
Функция должна формировать строку, а печать должна быть снаружи

2021-04-25 14:01 UTC, shahlar-mamedov commented on pract2/run.py
> +            arraymax = array
![image](https://user-images.githubusercontent.com/73404604/115995873-a63c5e00-a5e5-11eb-8ed0-bfc2256711b5.png)
Станислав Геннадьевич, в методичке которую вы нам выслали, написано: "Написать функцию, которая генерирует несколько массивов случайных чисел и возвращает тот, в котором сумма элементов наибольшая", а Вы делаете замечание: "Функция должна искать массив с наибольшей суммой элементов, а не генерировать массивы".
Наша программа работает корректно и результат программы удовлетворяет условию задания.

2021-05-21 11:20 UTC, merged